#auth_enabled: false
#auth_token: "XXX"
#db_path: habits.db
#api_base_url: http://localhost:3000
#log_level: info

#server:
#  host: 0.0.0.0
#  port: 3000
#  tls:
#    enabled: false
#    cert_file: ""
#    key_file: ""

#oidc_providers:
# - name: kanidm
#   # any valid ULID; needs to remain stable but is arbitrary
#   id: "01K5JMC5CM2FQGQ6AYVJEYKMVJ"
#   issuer_url: "https://idm.example.com/oauth2/openid/<your-client-id>"
#   client_id: "your-client-id"
#   client_secret: "your-client-secret"
#   redirect_url: "https://habits.example.com/auth/callback/01K5JMC5CM2FQGQ6AYVJEYKMVJ"
#   scopes: ["openid", "profile", "offline_access"]

# nudge:
#   notify_email: "me@example.com"
#   resend_api_key: "your-api-key"
#   threshold_hours: 24
