apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: habits

resources:
  - namespace.yaml
  - server-pvc.yaml
  - server-deployment.yaml
  - server-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

configMapGenerator:
  - name: habits-server-config
    files:
      - config.yaml
  - name: habits-frontend-caddyfile
    files:
      - Caddyfile

images:
  - name: ghcr.io/brk3/habits
    newTag: latest
  - name: ghcr.io/brk3/habits-frontend
    newTag: latest
